#!/usr/bin/env python3
"""Regenerates src/main/kotlin/com/chessapp/bot/OpeningBookData.kt from Lichess's open
chess-openings dataset (CC0): https://github.com/lichess-org/chess-openings

Run once on a dev machine (needs network + `pip install chess`); the generated file is checked in,
so builds and the shipped app/web bot never touch the network.

    python tools/generate_opening_book.py [--max-plies 16]
"""
import argparse
import io
import urllib.request
from pathlib import Path

import chess
import chess.pgn

BASE = "https://raw.githubusercontent.com/lichess-org/chess-openings/master/"
FILES = ["a.tsv", "b.tsv", "c.tsv", "d.tsv", "e.tsv"]
OUT = Path(__file__).resolve().parent.parent / "src/main/kotlin/com/chessapp/bot/OpeningBookData.kt"
CHUNK_BYTES = 40_000  # JVM class-file string constants max out at 65535 bytes


def fetch(name):
    with urllib.request.urlopen(BASE + name) as r:
        return r.read().decode("utf-8")


def line_to_uci(pgn_moves, max_plies):
    game = chess.pgn.read_game(io.StringIO(pgn_moves))
    board = game.board()
    out = []
    for move in game.mainline_moves():
        out.append(move.uci())
        board.push(move)
    return out[:max_plies]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--max-plies", type=int, default=16)
    args = ap.parse_args()

    lines = set()
    for name in FILES:
        for row in fetch(name).splitlines()[1:]:
            parts = row.split("\t")
            if len(parts) < 3:
                continue
            uci = line_to_uci(parts[2], args.max_plies)
            if uci:
                lines.add(" ".join(uci))
    ordered = sorted(lines)

    chunks, cur, size = [], [], 0
    for ln in ordered:
        if size + len(ln) + 1 > CHUNK_BYTES and cur:
            chunks.append("\n".join(cur))
            cur, size = [], 0
        cur.append(ln)
        size += len(ln) + 1
    if cur:
        chunks.append("\n".join(cur))

    body = ",\n".join('        """' + c + '"""' for c in chunks)
    OUT.write_text(
        "package com.chessapp.bot\n\n"
        "// GENERATED by tools/generate_opening_book.py from lichess-org/chess-openings (CC0). "
        "Do not edit by hand.\n"
        "// One UCI move sequence per line, each truncated to %d plies.\n"
        "internal object OpeningBookData {\n"
        "    val CHUNKS: List<String> = listOf(\n%s\n    )\n"
        "}\n" % (args.max_plies, body),
        encoding="utf-8",
    )
    print(f"{len(ordered)} lines in {len(chunks)} chunks -> {OUT}")


if __name__ == "__main__":
    main()
